### ISSUE TITLE
IOError: malloc error

### ISSUE THREAD

**Issue by tauqueer28** [holgern/pyedflib#11]
Code:
import pyedflib
import numpy as np
f = pyedflib.EdfReader("example.edf")
n = f.signals_in_file
signal_labels = f.getSignalLabels()
sigbufs = np.zeros((n,f.getNSamples()[0]))
for i in np.arange(n):
    sigbufs[i,:] = f.readSignal(i)
print sigbufs

####################

Error:

/usr/bin/python2.7 "/media/tauqs/main_partition/Tauqueer/Academics/8th Sem/BTP/Preprocessing.py"
Traceback (most recent call last):
  File "/media/tauqs/main_partition/Tauqueer/Academics/8th Sem/BTP/Preprocessing.py", line 3, in <module>
    f = pyedflib.EdfReader("example.edf")
  File "_pyedflib.pyx", line 91, in pyedflib._extensions._pyedflib.CyEdfReader.__init__ (pyedflib/_extensions/_pyedflib.c:2519)
  File "_pyedflib.pyx", line 125, in pyedflib._extensions._pyedflib.CyEdfReader.open (pyedflib/_extensions/_pyedflib.c:3076)
  File "_pyedflib.pyx", line 101, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok (pyedflib/_extensions/_pyedflib.c:2679)
IOError: malloc error

Process finished with exit code 1

**Comment by bollaking** [comment]
I can recreate with:
```
import pyedflib
f = pyedflib.EdfReader("example.edf")

```
my file is ~25MB
I am using python3.4

**Comment by fwahl711** [comment]
same issue here.

**Comment by holgern** [comment]
Can you retry with the newest version?
Does it work with smaller files?

**Comment by holgern** [comment]
I thinkt this issue can be closed.
