### ISSUE TITLE
Wrong signal sample rate if duration of a data record in EDF header is not 1 second 

### ISSUE THREAD

**Issue by Ari-PP** [holgern/pyedflib#179]
Sample code:

f = pyedflib.EdfReader( filename )
labels = f.getSignalLabels()
SampleRate = f.getSignalHeader(labels.index("Audio Volume"))['sample_rate'] 

SampleRate is ok if "duration of a data record" in EDF header is 1.
SampleRate is 10x real value if "duration of a data record" in EDF header is 10. 
SampleRate should be divided by "duration of a data record".

This seems to be broken in 0.1.23 and been broken ever since.

**Comment by skjerns** [comment]
This is due to a bug that was introduced recently

Does installing from this branch fix the issue for you? https://github.com/holgern/pyedflib/tree/issue148_samplerate2

**Comment by Ari-PP** [comment]
Installing issue148 fails. All Python modules have been installed from requirements-test.txt, Cython and gcc exists.

Traceback (most recent call last):
  File "setup.py", line 268, in <module>
    setup(
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by Ari-PP** [comment]
I can't test since issue148_samplerate2 did not install even if requirements-test.txt, Cython and compilers were installed. There is some problem with setuptools call when running "python setup.py build":

Traceback (most recent call last):
  File "setup.py", line 268, in <module>
    setup(
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/ari/.local/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by holgern** [comment]
I will create a new release

**Comment by skjerns** [comment]
There is a fix in PR #159, if you install from that branch it should be fine.

@holgern would you have time to have a look and merge PR? It quite a major bug that should be addressed

**Comment by DaveMtl** [comment]
Hi, just adding my voice to this issue, would love to see it fixed.

**Comment by tecamenz** [comment]
Hi, I also would love to see this fixed! Any updates so fare?

**Comment by skjerns** [comment]
nope, not really. If anyone wants to review the PR and give it a go I'd be glad :)

**Comment by gcathelain** [comment]
> nope, not really. If anyone wants to review the PR and give it a go I'd be glad :)

I can review it

**Comment by skjerns** [comment]
Merged and released 🥳 #159
