### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shape' thrown by writeSamples

### ISSUE THREAD

**Issue by quarterturn** [holgern/pyedflib#18]
exception:
Traceback (most recent call last):
  File "accellog.py", line 99, in <module>
    main(sys.argv[1:])
  File "accellog.py", line 78, in main
    f.writeSamples(data_list)
  File "/usr/local/lib/python2.7/dist-packages/pyedflib/edfwriter.py", line 661, in writeSamples
    lastSampleInd = int(np.max(data_list[i].shape) - ind[i])
AttributeError: 'str' object has no attribute 'shape'

[accellog.py.zip](https://github.com/holgern/pyedflib/files/1123173/accellog.py.zip)

**Comment by quarterturn** [comment]
I don't think I'm using it correctly as the examples work, but I have no idea how to write a stream vs. a complete list as in the provided write example.

**Comment by holgern** [comment]
data_list must contain only numbers and not strings as in your example

**Comment by quarterturn** [comment]
If I make a very simple example with `data = [1, 2, 3]` and then `f.writeSamples(data)` it throws the same exception. Is it something to do with needing an int from numpy vs a regular int?

**Comment by holgern** [comment]
At the moment only numpy array are allowed.

I will fix this!

**Comment by quarterturn** [comment]
Getting closer.
New code:
`
     63     while True:
     64         try:
     65             # read line from serial
     66             data = ser.readline()
     67             # split at commas and convert to int
     68             myList = np.fromstring(data, dtype=int, sep=",")
     69             # if we read three items
     70             if myList.shape[0] == 3:
     71                 print(myList)
     72                 try:
     73                     f.writeSamples(myList)
     74                 except IOError:
     75                     print("Unable to write to file %s" % (outfile))
     76                     break
     77                 except KeyboardInterrupt:
     78                     print("Exiting.")
     79                     sys.exit()
`
throws error:
`[1016 3068 2548]
Traceback (most recent call last):
  File "accellog.py", line 96, in <module>
    main(sys.argv[1:])
  File "accellog.py", line 73, in main
    f.writeSamples(myList)
  File "/usr/local/lib/python2.7/dist-packages/pyedflib/edfwriter.py", line 661, in writeSamples
    lastSampleInd = int(np.max(data_list[i].shape) - ind[i])
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2263, in amax
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
`

**Comment by quarterturn** [comment]
Any update? Seems like there's still a numpy issue in the library.

**Comment by holgern** [comment]
if samplerate is 1000, then please collect 1000 samples and write them
with writePhysicalSamples(x)

You can only write blockes and not sample by sample.

**Comment by quarterturn** [comment]
I have a feeling I don't quite grasp how setSignalHeaders relates to the format the data is passed to writePhysicalSamples.

In my instance, I need to record three simultaneous channels of data from an accellerometer (x,y, and z). I've got definitions for each axis I append to channel_info, and then setSignalHeaders(ch_dict).

My guess was f.writePhysicalSamples(list) was looking for a numpy array of channels x samplerate. However, I get "Buffer has wrong number of dimensions (expected 1, got 2)" so that can't be right.

Is f.writePhysicalSamples(list) looking for one channel of samplerate samples at a time, for each channel in setSignalHeaders?

**Comment by quarterturn** [comment]
I have figured it out. You must create an numpy array of samplerate * channels, fill it with your data, eg: x,y,z,x,y,z... and then f.writePhysicalSamples(array) once it is full. Edfbrowser says the headers are wrong, but if you use "Tools -> Header Editor" and just save the file, it will then open it without complaint. I'm not sure it fully looks right graphed out - it is as if it is interleaving the channels - but it is a start.

I've attached my code. Thanks for your help.
[accellog.py.zip](https://github.com/holgern/pyedflib/files/1283225/accellog.py.zip)
