### ISSUE TITLE
Numpy 2 Support

### ISSUE THREAD

**Issue by fehrlich** [holgern/pyedflib#262]
The current version does not run with numpy > 2.
On a clean setup:
- pip install numpy
- pip install pyedflib

run 
```python
import pyedflib
```

Output
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/pyedflib/lib/python3.12/site-packages/pyedflib/__init__.py", line 9, in <module>
    from ._extensions._pyedflib import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/pyedflib/lib/python3.12/site-packages/pyedflib/__init__.py", line 9, in <module>
    from ._extensions._pyedflib import *
  File "pyedflib/_extensions/_pyedflib.pyx", line 1, in init pyedflib._extensions._pyedflib
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by skjerns** [comment]
Can you try installing from the main branch? It should already be fixed, bit we still have to make a release

**Comment by skjerns** [comment]
should be fixed now :) try `pip install pyedflib --upgrade`

**Comment by skjerns** [comment]
No worries! It was already fixed I just forgot to make a release
