### ISSUE TITLE
Ignoring OSError: the file is not EDF(+) or BDF(+) compliant (starttime)

### ISSUE THREAD

**Issue by doktorneergaard** [holgern/pyedflib#35]
I have a bunch of EDFs that I need to process as part of a Python data pipeline, but I am running into some problems with a large portion of them. The error comes from the fact that start time in some of the files have been processed wrongly before, so that the 'seconds' variable is more than 60 seconds in value.

I tried modifying the check_open_ok function in _pyedflib.pyx to
```
def check_open_ok(self,result):
    if result == 0:
        return True
    elif self.hdr.filetype in ['EDFLIB_FILE_ERRORS_STARTDATE', 'EDFLIB_FILE_ERRORS_STARTTIME']:
        return True
    else:
        raise IOError, open_errors[self.hdr.filetype]
        # return False
```
and then building again, but I still get the same error: 
```
File "pyedflib/_extensions/_pyedflib.pyx", line 116, in pyedflib._extensions._pyedflib.CyEdfReader.__init__
  File "pyedflib/_extensions/_pyedflib.pyx", line 157, in pyedflib._extensions._pyedflib.CyEdfReader.open
  File "pyedflib/_extensions/_pyedflib.pyx", line 129, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok
OSError: the file is not EDF(+) or BDF(+) compliant (starttime)
```

Would you know of any other way to skip this specific check, or am I perhaps not implementing the changes correctly (ie. building incorrectly? I am not an expert in modifying Python packages).

**Comment by aneergaard** [comment]
So, I did some more digging around, and I believe I have found the place where the issue arises in the C code. In the definition of the edfhdrblock struct in edflib.c, there is the following code block:

```
/********************* STARTTIME *********************************************/

  strncpy(scratchpad, edf_hdr + 176, 8);
  scratchpad[8] = 0;
  for(i=0; i<8; i++)
  {
    if((scratchpad[i]<32)||(scratchpad[i]>126))
    {
      *edf_error = EDFLIB_FILE_ERRORS_STARTTIME;
      free(edf_hdr);
      free(edfhdr);
      return(NULL);
    }
  }

  error = 0;

  if((edf_hdr[178]!='.')||(edf_hdr[181]!='.'))  error = 1;
  if((edf_hdr[176]<48)||(edf_hdr[176]>57))      error = 1;
  if((edf_hdr[177]<48)||(edf_hdr[177]>57))      error = 1;
  if((edf_hdr[179]<48)||(edf_hdr[179]>57))      error = 1;
  if((edf_hdr[180]<48)||(edf_hdr[180]>57))      error = 1;
  if((edf_hdr[182]<48)||(edf_hdr[182]>57))      error = 1;
  if((edf_hdr[183]<48)||(edf_hdr[183]>57))      error = 1;

  strncpy(scratchpad, edf_hdr + 176, 8);

  if(error)
  {
    strncpy(scratchpad, edf_hdr + 176, 8);
    scratchpad[8] = 0;
    *edf_error = EDFLIB_FILE_ERRORS_STARTTIME;
    free(edf_hdr);
    free(edfhdr);
    return(NULL);
  }

  scratchpad[2] = 0;
  scratchpad[5] = 0;
  scratchpad[8] = 0;

  if(edflib_atof_nonlocalized(scratchpad)>23)
  {
    strncpy(scratchpad, edf_hdr + 176, 8);
    scratchpad[8] = 0;
    *edf_error = EDFLIB_FILE_ERRORS_STARTTIME;
    free(edf_hdr);
    free(edfhdr);
    return(NULL);
  }

  if(edflib_atof_nonlocalized(scratchpad+3)>59)
  {
    strncpy(scratchpad, edf_hdr + 176, 8);
    scratchpad[8] = 0;
    *edf_error = EDFLIB_FILE_ERRORS_STARTTIME;
    free(edf_hdr);
    free(edfhdr);
    return(NULL);
  }

  if(edflib_atof_nonlocalized(scratchpad+6)>59)
  {
    strncpy(scratchpad, edf_hdr + 176, 8);
    scratchpad[8] = 0;
    *edf_error = EDFLIB_FILE_ERRORS_STARTTIME;
    free(edf_hdr);
    free(edfhdr);
    return(NULL);
  }

  edfhdr->starttime_hour = edflib_atof_nonlocalized(scratchpad);
  edfhdr->starttime_minute = edflib_atof_nonlocalized(scratchpad + 3);
  edfhdr->starttime_second = edflib_atof_nonlocalized(scratchpad + 6);

  edfhdr->l_starttime = 3600 * edflib_atof_nonlocalized(scratchpad);
  edfhdr->l_starttime += 60 * edflib_atof_nonlocalized(scratchpad + 3);
  edfhdr->l_starttime += edflib_atof_nonlocalized(scratchpad + 6);

  edfhdr->l_starttime *= EDFLIB_TIME_DIMENSION;
```
I am pretty certain that the correct checks can be subverted here, but I am unsure what the numbers signify.

**Comment by prats2018** [comment]
Hi, I am new to this tool.Please help me solve below error to convert .edf to csv file,
cd /work/prathushal/pyed/pyedflib-master/demo ;
python3.6 readEDFFile.py FT_7RST39388.000.3_25C_SmartScale02_20190427_23h39m12s_lot.edf

I get the error below.
### Traceback (most recent call last):
  File "readEDFFile.py", line 12, in <module>
    f = pyedflib.EdfReader("FT_7RST39388.000.3_25C_SmartScale02_20190427_23h39m12s_lot.edf")
  File "pyedflib/_extensions/_pyedflib.pyx", line 116, in pyedflib._extensions._pyedflib.CyEdfReader.__init__
  File "pyedflib/_extensions/_pyedflib.pyx", line 155, in pyedflib._extensions._pyedflib.CyEdfReader.open
  File "pyedflib/_extensions/_pyedflib.pyx", line 127, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok
OSError: the file is not EDF(+) or BDF(+) compliant (it contains format errors)

I am running this on centos-7 machine.

[FT_7RST39388.000.3_25C_SmartScale02_20190427_23h39m12s_lot.txt](https://github.com/holgern/pyedflib/files/3171114/FT_7RST39388.000.3_25C_SmartScale02_20190427_23h39m12s_lot.txt)



Thanks
Prats
