### ISSUE TITLE
PR #44 seems to be causing test failures

### ISSUE THREAD

**Issue by dthkao** [holgern/pyedflib#54]
Was PR #44 tested in Python 3? When I run test_edfwriter.py in py3 I see:

`ValueError: Buffer dtype mismatch, expected 'int32_t' but got 'long'
`
This seems to stem from `blockwrite_digital_samples` in _pyedflib.pyx explicitly expecting int32, but np.int (equivalently the builtin int) in python has a version-dependent underlying dtype.

Does using np.int32 make more sense here?

**Comment by dthkao** [comment]
Actually this appears to be failing in 2.7 as well.

```
$ python test_edfwriter.py 
..........E.
======================================================================
ERROR: test_SampleWriting_digital (__main__.TestEdfWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_edfwriter.py", line 340, in test_SampleWriting_digital
    f.writeSamples(data_list, digital=True)
  File "/home/davidkao/.local/lib/python2.7/site-packages/pyedflib/edfwriter.py", line 691, in writeSamples
    self.blockWriteDigitalSamples(dataOfOneSecond)
  File "/home/davidkao/.local/lib/python2.7/site-packages/pyedflib/edfwriter.py", line 634, in blockWriteDigitalSamples
    return blockwrite_digital_samples(self.handle, data)
  File "pyedflib\_extensions\_pyedflib.pyx", line 420, in pyedflib._extensions._pyedflib.blockwrite_digital_samples
ValueError: Buffer dtype mismatch, expected 'int32_t' but got 'long'

----------------------------------------------------------------------
Ran 12 tests in 0.013s

FAILED (errors=1)

```
