### ISSUE TITLE
WriteAnnotation fails on linux

### ISSUE THREAD

**Issue by bwmhamad** [holgern/pyedflib#68]
Hello everyone,

There's a problem when writing annotation on Linux.
This error doesn't occur on Windows for the same code.
Following is a block of code that causes exception:
```python
number_of_channels = len(data)
writer = pyedflib.EdfWriter(filename, number_of_channels, file_type=pyedflib.FILETYPE_EDFPLUS)
...
for note in annotations:
	logging.info("Writing %s, %f, %f",note[0],note[1],note[3])
	writer.writeAnnotation("test",1,-1)
````

Following is back-trace of the exception:
```
Traceback (most recent call last):
  File "builder.py", line 58, in <module>
    main()
...
    create_edf_file(path, data, sample_rate, annotations, labels)
  File "builder/edfbuilder.py", line 49, in create_edf_file
    writer.writeAnnotation("test",1,-1)
  File "builder/pyedflib/edfwriter.py", line 734, in writeAnnotation
    return write_annotation_utf8(self.handle, np.round(onset_in_seconds*10000).astype(int), np.round(duration_in_seconds*10000).astype(int), du(description))
  File "<__array_function__ internals>", line 6, in round_
  File "builder/numpy/core/fromnumeric.py", line 3599, in round_
    return around(a, decimals=decimals, out=out)
  File "<__array_function__ internals>", line 6, in around
  File "builder/numpy/core/fromnumeric.py", line 3224, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "builder/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "builder/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: ufunc 'rint' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
More information about the environment:
```
OS: Ubuntu 16.04.6 LTS
Linux: 4.15.0-72-generic
numpy==1.18.1
python: Python 3.7.6
```

Thanks in advance.

**Comment by bwmhamad** [comment]
Sorry the order of arguments were misplaced. Closing issue.
