### ISSUE TITLE
Handling of wrong paths

### ISSUE THREAD

**Issue by rob-med** [holgern/pyedflib#7]
Currently the library does not handle gracefully when a wrong file path is passed to pyedflib.EdfReader() since it raises a generic 'malloc error' (see trace below):

> Traceback (most recent call last):
  f = pyedflib.EdfReader(data_EDF)
  File "pyedflib\_extensions\_pyedflib.pyx", line 91, in pyedflib._extensions._pyedflib.CyEdfReader.__init__ (pyedflib\_extensions\_pyedflib.c:2674)
  File "pyedflib\_extensions\_pyedflib.pyx", line 125, in pyedflib._extensions._pyedflib.CyEdfReader.open (pyedflib\_extensions\_pyedflib.c:3287)
  File "pyedflib\_extensions\_pyedflib.pyx", line 101, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok (pyedflib\_extensions\_pyedflib.c:2846)
IOError: malloc error

**Comment by holgern** [comment]
Handling of wrong path is fixed in the current master

**Comment by rob-med** [comment]
Thank you!
